FROM grafana/grafana:10.0.10

COPY grafana/provisioning/datasources /etc/grafana/provisioning/datasources
COPY grafana/provisioning/dashboards /etc/grafana/provisioning/dashboards
COPY grafana/dashboards /var/lib/grafana/dashboards
